[book]
title = "The Rizin Handbook: A Guide to Reverse Engineering with the Rizin Framework"
author = "Rizin Organization"
description = "This book focuses on the Rizin reverse engineering framework"

[build]
create-missing = false

[output.html.search]
limit-results = 15
